### ISSUE TITLE
Doesn't Compile Delphi 10 Seattle

### ISSUE THREAD

**Issue by johnnyce** [marcieldeg/consolemessagereceiver#2]
Happy 2021. I really appreciate the code; unfortunately, I couldn't get it to compile in Delphi 10 (what else is new?). I'll dig into it. Odds are its a simple datatype fix?

Here's the error message and offending code. 
[dcc32 Error] UConsoleMessageReceiver.pas(152): E2033 Types of actual and formal var parameters must be identical
[dcc32 Fatal Error] ConsoleMessageReceiver.dpk(33): F2063 Could not compile used unit 'UConsoleMessageReceiver.pas'
Failed

    if Supports(Self.FWebBrowser.Document, IOleCommandTarget, Comm) then
      **Comm.Exec(@CGID_MSHTML, Action, OLECMDEXECOPT_DODEFAULT, IDeveloperConsoleMessageReceiver(Self), EmptyParam);**

I'll try to attach a screen shot of my Delphi version since I know from experience that has a huge impact on datatypes.
![LowLevel_Delphi](https://user-images.githubusercontent.com/47607563/113324217-dcd3d100-92e4-11eb-812d-146ba1ae6578.png)

Thanks,
Johnny

**Comment by marcieldeg** [comment]
Hi Johnny, thanks for reporting. This bug is fixed, please download again and test.
